---
abstract: 'Langinfo and POSIX functions with wide-char strings.'
author:
  - 'Kevin Ryde <user42@zip.com.au>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.133380'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: I18N-Langinfo-Wide
no_index:
  directory:
    - t
    - inc
    - devel
requires:
  Encode: 2.25
  I18N::Langinfo: 0
  perl: 5.008001
resources:
  homepage: http://user42.tuxfamily.org/i18n-langinfo-wide/index.html
  license: http://www.gnu.org/licenses/gpl.html
version: 8
